In [2]:
import numpy as np

In [13]:
a = [1,2,3,4,5]
b = np.asarray(a)
print(a,b)
type(b)
a

[1, 2, 3, 4, 5] [1 2 3 4 5]


[1, 2, 3, 4, 5]

In [11]:
for e in b:
    print(e)

1
2
3
4
5


In [14]:
b.dtype

dtype('int64')

In [17]:
np.asarray([1,"Hola",True])

array(['1', 'Hola', 'True'], dtype='<U21')

In [18]:
a = [1,2,3]
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [19]:
a = np.asarray([1,2,3])
a*3

array([3, 6, 9])

In [22]:
z = [[1,2,3],[4,5,6],[7,8,9]]
print(z)
a = np.asarray(z)
print(a)
a*10

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
q = np.random.random((3,4))
q

array([[0.67864951, 0.52234345, 0.86082736, 0.97088962],
       [0.96447712, 0.99771957, 0.6608896 , 0.53533162],
       [0.64149115, 0.35591346, 0.52510013, 0.79515659]])

In [33]:
q.size

12

In [36]:
print(q.shape,len(q.shape))

(3, 4) 2


In [42]:
q = np.random.random((3,3))
print(q)
print(q * np.eye(3))

m = q * (np.ones((3,3)) - np.eye(3))
print(m)

[[0.64714849 0.30781077 0.35101985]
 [0.67699961 0.07615465 0.17338253]
 [0.29517093 0.17084258 0.12623513]]
[[0.64714849 0.         0.        ]
 [0.         0.07615465 0.        ]
 [0.         0.         0.12623513]]
[[0.         0.30781077 0.35101985]
 [0.67699961 0.         0.17338253]
 [0.29517093 0.17084258 0.        ]]


In [43]:
m

array([[0.        , 0.30781077, 0.35101985],
       [0.67699961, 0.        , 0.17338253],
       [0.29517093, 0.17084258, 0.        ]])

In [47]:
m.sum(axis=1)

array([0.65883062, 0.85038214, 0.46601351])

In [50]:
q = np.random.random((3,3,3))

array([[[0.22062597, 0.63535964, 0.80868984],
        [0.17299902, 0.36462376, 0.12151228],
        [0.99684167, 0.6850623 , 0.24006534]],

       [[0.39524345, 0.51250261, 0.74571646],
        [0.40310553, 0.28715958, 0.55359443],
        [0.75483052, 0.62035331, 0.26912153]],

       [[0.52189068, 0.74482246, 0.28158607],
        [0.01702764, 0.13729105, 0.68505545],
        [0.17247847, 0.64094163, 0.95150435]]])

In [60]:
a = np.random.random((3,3))
b = a.tolist()
print(a)
print(b[0][1])
print(a[0,1])

[[0.70881535 0.39572096 0.62165933]
 [0.78541648 0.07945728 0.55227925]
 [0.45426132 0.82037177 0.34894975]]
0.3957209593833342
0.3957209593833342


In [73]:
q = np.random.random((3,3,3))
print(q)
print(q[:,:,1])
print(q[:,:,1].sum(axis=0))

[[[0.00709577 0.3060545  0.12793482]
  [0.33087423 0.34566207 0.66912751]
  [0.83911817 0.45570459 0.17499267]]

 [[0.79430867 0.73858864 0.4681041 ]
  [0.08020842 0.69944168 0.76229857]
  [0.62969903 0.38374288 0.99871188]]

 [[0.57391804 0.54928161 0.14756512]
  [0.7435205  0.95197313 0.90863508]
  [0.97896668 0.17306974 0.37295828]]]
[[0.3060545  0.34566207 0.45570459]
 [0.73858864 0.69944168 0.38374288]
 [0.54928161 0.95197313 0.17306974]]
[1.59392474 1.99707687 1.01251722]


In [75]:
 np.random.random((3,3,3)).sum(axis=2)

array([[1.63939714, 1.02231172, 1.53909983],
       [1.35924912, 1.14433133, 0.94540449],
       [1.09298428, 1.67578147, 1.72357859]])

In [82]:
a = np.random.random((3,3))
b = np.random.random((3,3))
print(np.concatenate([a,b], axis=1))

[[0.26766634 0.49337369 0.6818081  0.85266959 0.78162944 0.49097814]
 [0.43772206 0.36612462 0.39537829 0.03310979 0.6171175  0.49200201]
 [0.25923923 0.72601238 0.14933393 0.92263023 0.79413812 0.11492201]]


In [89]:
np.arange(10,dtype="float").dtype

dtype('float64')

In [106]:
np.expand_dims(np.arange(9).reshape((3,3)),axis=0)

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [113]:
z = np.arange(9).reshape((3,3))
print(z)
z.std(axis=1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0.81649658, 0.81649658, 0.81649658])

In [119]:
z = np.arange(9).reshape((3,3))
print(z*2)
print(np.dot(z,z))

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


In [124]:
np.random.random((4,4)).round(2)

array([[0.44, 0.54, 0.95, 0.31],
       [0.64, 0.55, 0.69, 0.19],
       [0.24, 0.22, 0.49, 0.51],
       [0.47, 0.66, 0.96, 0.53]])

In [3]:
a = np.arange(10)
print(a/0)

[nan inf inf inf inf inf inf inf inf inf]


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
