In [3]:
from scipy import linalg
import numpy as np

In [12]:
A = np.array([1,3,5,2,5,1,2,3,8]).reshape(3,3)
b = np.array([[10,8,3]]).T
print(A)
print(b)

[[1 3 5]
 [2 5 1]
 [2 3 8]]
[[10]
 [ 8]
 [ 3]]


In [13]:
[x],[y],[z] = linalg.solve(A,b)
print(x,y,z)

-9.280000000000001 5.16 0.76


In [18]:
x,y,z = np.hstack(linalg.solve(A,b))
print(x,y,z)

-9.280000000000001 5.16 0.76


In [19]:
linalg.det(A)

-25.000000000000004

In [27]:
from scipy.stats import tmean
tmean(range(0,11),limits=(1,5))

3.0

In [33]:
import pandas as pd

a = np.array(["foo", "foo", "foo", "foo", "bar", "bar",
              "bar", "bar", "foo", "foo", "foo"], dtype=object)
b = np.array(["one", "one", "one", "two", "one", "one",
              "one", "two", "two", "two", "one"], dtype=object)
c = np.array(["dull", "dull", "shiny", "dull", "dull", "shiny",
              "shiny", "dull", "shiny", "shiny", "shiny"],
             dtype=object)

df = pd.DataFrame({"a":a,"b":b,"c":c})

display(df)
dfz = pd.crosstab(df.a, [df.b, df.c])
display(dfz)
pd.crosstab(df.a, [df.b])

a    b      c
0   foo  one   dull
1   foo  one   dull
2   foo  one  shiny
3   foo  two   dull
4   bar  one   dull
5   bar  one  shiny
6   bar  one  shiny
7   bar  two   dull
8   foo  two  shiny
9   foo  two  shiny
10  foo  one  shiny

b    one        two      
c   dull shiny dull shiny
a                        
bar    1     2    1     0
foo    2     2    1     2

b    one  two
a            
bar    3    1
foo    4    3

In [47]:
dfz["one"]

c    dull  shiny
a               
bar     1      2
foo     2      2

In [63]:
# Hierarchy index access by label
q = dfz.T
display(q)
q.iloc[q.index.isin(["dull"],level=1)]

a          bar  foo
b   c              
one dull     1    2
    shiny    2    2
two dull     1    1
    shiny    0    2

a         bar  foo
b   c             
one dull    1    2
two dull    1    1